### PR TITLE
Display validation errors on NewPassword page

### LINKED ISSUE #468: Password validation errors are not shown
### What I'm trying to achieve
To set password as a new staff user.

### Steps to reproduce the problem
1. Create a new staff user through the dashboard.
2. Receive an email with the link to set up password and click it.
3. Provide a password that doesn't validate against password rules, e.g. too short.

### What I expected to happen
To see a validation error.

### Screenshots

image

### PR DESCRIPTION
**Pull request by gabmartinez**
I want to merge this change because it displays the validation errors on the New Password Page.

fix #468 

### Pull Request Checklist

1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Translated strings are extracted.
1. [x] Number of API calls is optimized.
1. [x] The changes are tested.
1. [x] Type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

File: src/auth/views/NewPassword.tsx [hunk 1]
```diff
@@ -8,19 +8,27 @@ import NewPasswordPage, {
...
+import {
+  SetPassword,
+  SetPassword_setPassword_errors
+} from "../types/SetPassword";
 import { NewPasswordUrlQueryParams } from "../urls";
 
 const NewPassword: React.FC<RouteComponentProps> = ({ location }) => {
   const navigate = useNavigator();
   const { loginByToken } = useUser();
+  const [errors, setErrors] = React.useState<
```
Comment (dominik-zeglen) [inline src/auth/views/NewPassword.tsx:20]: The state here is not needed. `SetPasswordMutation` returns `setPasswordOpts`, which has `data` property, allowing us to access `data.setPassword.errors`, which we can directly convey to `NewPasswordPage` as prop. I'll look like this
```
<NewPasswordPage
  errors={setPasswordOpts.data.?.setPassword.errors || []}
  ...
/>
```

Comment (gabmartinez) [reply src/auth/views/NewPassword.tsx]: You're right. done.

Thank you ;)
