### PR TITLE
Handle rich text editor content error

### LINKED ISSUE #356: Can't view product details for product with incorrect descriptionJson
### What I'm trying to achieve
I want to see the product edit view.  I have descriptionJson without Drafttail format.

### What I expected to happen
See product edit view with empty description and notify about an error in description.

### PR DESCRIPTION
**Pull request by dominik-zeglen**
I want to merge this change because it fixes #356 

### Screenshots
Screenshot 2020-02-03 at 12 19 12

### Pull Request Checklist

1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Translated strings are extracted to `.pot` file.
1. [x] Number of API calls is optimized.
1. [x] The changes are tested.
1. [x] Type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

File: src/components/RichTextEditor/RichTextEditor.tsx [hunk 1]
```diff
@@ -226,58 +236,71 @@ const RichTextEditor: React.FC<RichTextEditorProps> = props => {
...
+            enableLineBreak
+            entityTypes={[
+              {
+                attributes: ["url"],
+                decorator: LinkEntity,
+                icon: <LinkIcon className={classes.linkIcon} />,
+                source: LinkSource,
+                type: ENTITY_TYPE.LINK
+              }
+              // {
```
Comment (krzysztofwolski) [inline src/components/RichTextEditor/RichTextEditor.tsx]: 👾
