### PR TITLE
Handle invalid token error

### LINKED ISSUE #352: Crash when stored JWT token is no longer valid
### What I'm trying to achieve
Being able to use the dashboard after my JWT token is no-longer valid (be redirect to the login page).

### Steps to reproduce the problem
1. Login to the dashboard
2. Alter the secret key (`SECRET_KEY`) and restart
3. Reload the dashboard
3. Response: `{"data": {"tokenVerify": null}}`,
  Error: `TypeError: "n.data.tokenVerify is null"`

### What I expected to happen
Redirection to the login page.

**System information**
Browser: Firefox/71.0

### PR DESCRIPTION
**Pull request by dominik-zeglen**
I want to merge this change because it resolves #352 

### Pull Request Checklist

1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Translated strings are extracted to `.pot` file.
1. [x] Number of API calls is optimized.
1. [x] The changes are tested.
1. [x] Type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

File: src/auth/AuthProvider.tsx [hunk 1]
```diff
@@ -90,9 +91,13 @@ class AuthProvider extends React.Component<
         );
       }
     } else {
-      if (tokenVerifyOpts.data && tokenVerifyOpts.data.tokenVerify.user) {
-        const user = tokenVerifyOpts.data.tokenVerify.user;
-        this.setState({ user });
+      if (maybe(() => tokenVerifyOpts.data.tokenVerify === null, false)) {
+        this.logout();
+      } else {
+        if (maybe(() => !!tokenVerifyOpts.data.tokenVerify.user, false)) {
```
Comment (krzysztofwolski) [inline src/auth/AuthProvider.tsx]:
```suggestion
        const user = maybe(() => tokenVerifyOpts.data.tokenVerify.user)
        if (user) this.setState({ user });
```
