### PR TITLE
Columns dialog clean attribute ids before send it to GridAttributes operation

### LINKED ISSUE #478: Invalid query data sent in product list
### What I'm trying to achieve
Get the product list.

### Steps to reproduce the problem
1. Go in product list (Catalogue > Product);
2. You should have a popup: "Saleor ran into an unexpected issue".

### What I expected to happen
Not have the popup "Saleor ran into an unexpected issue".

### What happened instead
I get a popup saying "Saleor ran into an unexpected issue", which is resulting from:

#### Query
```yaml
---
'5':
  operationName: GridAttributes
  query: |
    fragment PageInfoFragment on PageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
      __typename
    }

    query GridAttributes($first: Int!, $after: String, $ids: [ID!]!) {
      availableInGrid: attributes(first: $first, after: $after, filter: {availableInGrid: true, isVariantOnly: false}) {
        edges {
          node {
            id
            name
            __typename
          }
          __typename
        }
        pageInfo {
          ...PageInfoFragment
          __typename
        }
        totalCount
        __typename
      }
      grid: attributes(first: 25, filter: {ids: $ids}) {
        edges {
          node {
            id
            name
            __typename
          }
          __typename
        }
        __typename
      }
    }
  variables:
    first: 6
    ids:
    - isPublished
    - price
    - productType
```

#### Response
```yaml
5: 
 errors: 
  - 
   message: "{\"ids\": [{\"message\": \"Invalid ID specified.\", \"code\": \"\"}]}"
   locations: 
    - 
   line: 26
     column: 3
   path: 
    - 
   grid
   extensions: 
    exception: 
     code: GraphQLError
 data: 
  availableInGrid: 
   edges: 
    - 
   node: 
      id: QXR0cmlidXRlOjIx
      name: ABV
      __typename: Attribute
     __typename: AttributeCountableEdge
    - 
   node: 
      id: QXR0cmlidXRlOjE1
      name: "Bottle Size"
      __typename: Attribute
     __typename: AttributeCountableEdge
    - 
   node: 
      id: QXR0cmlidXRlOjE4
      name: "Bucket Size"
      __typename: Attribute
     __typename: AttributeCountableEdge
    - 
   node: 
      id: QXR0cmlidXRlOjE0
      name: Color
      __typename: Attribute
     __typename: AttributeCountableEdge
    - 
   node: 
      id: QXR0cmlidXRlOjIy
      name: "Cushion Size"
      __typename: Attribute
     __typename: AttributeCountableEdge
    - 
   node: 
      id: QXR0cmlidXRlOjE2
      name: Flavor
      __typename: Attribute
     __typename: AttributeCountableEdge
   pageInfo: 
    endCursor: "YXJyYXljb25uZWN0aW9uOjU="
    hasNextPage: true
    hasPreviousPage: false
    startCursor: "YXJyYXljb25uZWN0aW9uOjA="
    __typename: PageInfo
   totalCount: 11
   __typename: AttributeCountableConnection
  grid: null
```

### Versions
Dashboard: [05078112da4b015a243326c54ca341b2e2e1adc3](https://github.com/mirumee/saleor-dashboard/tree/05078112da4b015a243326c54ca341b2e2e1adc3)
Core: [987aff0dd59fbbf8ad00e922ea6a1931102f2372](https://github.com/mirumee/saleor/tree/987aff0dd59fbbf8ad00e922ea6a1931102f2372)

### PR DESCRIPTION
**Pull request by gabmartinez**
I want to merge this change because it resolves the issue that was sending invalid ids to GridAttributes operation and it was getting an error from the API and frozen the dialog to add/remove columns.

Fix #478 

### Pull Request Checklist

1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Translated strings are extracted.
1. [x] Number of API calls is optimized.
1. [x] The changes are tested.
1. [x] Type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by dominik-zeglen** [comment]
I have no idea what problem this PR solves. Would you mind explaining it?

**Comment by gabmartinez** [comment]
> I have no idea what problem this PR solves. Would you mind explaining it?

After the PR [5460](https://github.com/mirumee/saleor/pull/5460) the API is expecting valid IDs in the filter otherwise it will raise a GraphQLError. In the Dashboard, the feature to add more columns in the list of products was not working because we were sending invalid IDs and getting errors and it was not updating the list. So, now we are filtering the value to send only valid IDs to the API.

File: src/products/views/ProductList/ProductList.tsx [hunk 1]
```diff
@@ -215,9 +219,18 @@ export const ProductList: React.FC<ProductListProps> = ({ params }) => {
...
   );
 
+  const columnIdsFilter = columns => {
+    columns = columns.filter(column => isAttributeColumnValue(column));
+    columns.forEach(
+      (attribute, index, arr) =>
+        (arr[index] = getAttributeIdFromColumnValue(attribute))
+    );
+    return columns;
+  };
```
Comment (dominik-zeglen) [inline src/products/views/ProductList/ProductList.tsx:229]: I think this can be shortened to

```
  function filterColumnIds(columns: ProductListColumns[]) {
    return columns.filter(isAttributeColumnValue).map(getAttributeIdFromColumnValue)
  }
```

Comment (gabmartinez) [reply src/products/views/ProductList/ProductList.tsx:229]: cool, working on it. Thanks

Comment (gabmartinez) [reply src/products/views/ProductList/ProductList.tsx:229]: Also, we could move it to the util library to be able to reuse it in other places as we need it.

Comment (gabmartinez) [reply src/products/views/ProductList/ProductList.tsx]: Never mind, it's specific for the available query in that view. I updated the description to include issue #478 created today.

Done, please review it again and thank you for the feedback :)
