### PR TITLE
UI improvements

### LINKED ISSUE #101: UI improvements #4
There are some changes that we need to get done for the dashboard to fit the UI kit:

Overall
- [x] fix paddings - elements in cards should have 24px of paddings
- [x] checkboxes need to reflect UI kit checkboxes
- [x] update chips style - i've changed that upon a request ot improve contrasts.
- [x] when loading elements in tables elements in header row tend to move to far left of the table. Happens only on first load of the table
- [x] Change switches to checkboxes - @patrys noted that switches by standard should indicate immediate actions - which is mostly not the case in the system. Big Thanks - For more info come to @pwgryglak 
- [x] Implement new behaviour of "Visibility card" - this can be seen in UI guide. This needs to be changed based on changes with switch/checkboxes - For more info come to @pwgryglak 

Cards
- [x] Header of card has bigger paddings than content - should be the same

Restructure
- [x] update configuration view - both the structure and new icons - while at it those icons should also lose gradients.

Buttons:
- [x] Filter button on tables should be fixed
- [x] "on staging" secondary buttons in dark mode are white color instead of primary action color

Tables:
- [ ] Changing tabs on discounts, categories etc. scrolls whole page to the top. Shouldn't do that.
- [ ] ~~when going to prefiltered table from dashboard the chip which filter is on is empty~~
- [x] after typing something in search bar - save custom search should have more padding from table rows.
- [ ] ~~You should have an ability to filter order table to show fulfilled and partially fulfilled both. Should show elements that fulfill either one of the conditions.~~
- [x] Arrows on the bottom should be closer together. Also their styling should be different

Inputs:
- [x] input disabled state should reflect one in UI kit
- [x] inputs in filters should be changed accroding to UI kit
- [x] "Name" inputs tend to be 2/3 lenght of the card instead of full width
- [x] inputs without labels from UI should be 40px instead of 56px
- [x] borders on inputs should be changed
- [x] input autocomplete element should be changed based on UI kit
- [x] Inputs in "history" modules should reflect UI kit inputs
- [x] dropdowns do not show which element is selected.

Snackbars:
- [x] Design of snackbars should be changed to reflect those in UI Kit

Pickers:
- [ ] Implement Pickers for date inputs

Product Page:
- [x] After adding variants - hint text what variants are should not be shown.

### LINKED ISSUE #120: Remove address title from address cards
Request:
Remove address number title element from address cards in "Manage Addresses" view in customer section

### LINKED ISSUE #132: Change naming of buttons
As discussed in #87 we need to change names of several elements.

buttons and modals need to be changed accordingly:
- [x] Set all elements creating new records to: Create - on modals also. With some exceptions: Issue a gift card, Invite Staff, add address also add customer
- [x] All elements that assign (add records to something) - Buttons will be changed to assign -> Assign Products, Assign Countries etc. exception adding products to draft orders

In case of any questions ask me.

### PR DESCRIPTION
**Pull request by benekex2**
Closes #101 
Closes #132 
Closes #120

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted to `.pot` file.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

File: src/theme.ts [hunk 1]
```diff
@@ -74,14 +87,30 @@ export default (colors: IThemeColors): Theme =>
...
+      },
       MuiDialogContent: {
         root: {
           padding: "5px 24px 24px"
         }
       },
+      MuiFormControlLabel: {
+        root: {
+          display: "grid",
+          gridTemplateColumns: "50px 6fr"
```
[the remark this answers is not in the document]
Comment (benekex2) [reply src/theme.ts]: I need it in checkbox

File: src/theme.ts [hunk 2]
```diff
@@ -125,9 +158,16 @@ export default (colors: IThemeColors): Theme =>
           "&$shrink": {
             transform: "translate(12px, 6px) scale(0.75)"
           },
-          transform: "translate(14px, 14px) scale(1)"
+          transform: "translate(14px, 14px) scale(1)",
+          zIndex: 9
```
[the remark this answers is not in the document]
Comment (benekex2) [reply src/theme.ts]: To make sure label is always on top.

[the remark this answers is not in the document]
Comment (dominik-zeglen) [reply src/theme.ts]: But why, when it isn't on top when it should be?

File: src/theme.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (dominik-zeglen) [reply src/theme.ts]: If you need it in checkboxes, you should be doing it there, not globally.

File: src/components/RadioGroupField/RadioGroupField.tsx [hunk 3]
```diff
@@ -77,22 +77,22 @@ export const RadioGroupField = withStyles(styles, {
...
-            })
+            choices.map(choice => (
+              <FormControlLabel
+                value={choice.value}
+                className={classes.radioLabel}
+                control={<Radio color="primary" />}
+                label={
+                  <>
+                    {choice.label}
+                    <span className={classes.secondLabel}>
```
Comment (dominik-zeglen) [inline src/components/RadioGroupField/RadioGroupField.tsx]: I think there was a misunderstanding - I asked that we drop `secondLabel` instead of naming its class

File: src/components/VisibilityCard/VisibilityCard.tsx [hunk 4]
```diff
@@ -154,8 +148,10 @@ export const VisibilityCard = withStyles(styles, {
                   className={classes.setPublicationDate}
                   onClick={() => setPublicationDate(!isPublicationDate)}
                 >
-                  {" "}
-                  Set publication date
+                  {intl.formatMessage({
+                    defaultMessage: "Set publication date",
+                    description: "set publication date"
```
Comment (dominik-zeglen) [inline src/components/VisibilityCard/VisibilityCard.tsx]: Redundant

File: src/collections/components/CollectionDetailsPage/CollectionDetailsPage.tsx [hunk 5]
```diff
@@ -124,18 +128,40 @@ const CollectionDetailsPage: React.StatelessComponent<
...
-                    checked={data.isFeatured}
-                    disabled={disabled}
-                    name="isFeatured"
-                    onChange={change}
-                    label={intl.formatMessage({
-                      defaultMessage: "Feature on Homepage",
-                      description: "switch button"
-                    })}
-                  />
+                  <>
```
Comment (dominik-zeglen) [inline src/collections/components/CollectionDetailsPage/CollectionDetailsPage.tsx]: It should be possible to pass children without `React.Fragment`

File: src/components/RadioGroupField/RadioGroupField.tsx [hunk 6]
```diff
@@ -23,13 +23,17 @@ const styles = createStyles({
     "& > span": {
       padding: "6px"
     }
+  },
+  secondLabel: {
```
Comment (dominik-zeglen) [inline src/components/RadioGroupField/RadioGroupField.tsx]: Unused class

File: src/components/RadioGroupField/RadioGroupField.tsx [hunk 7]
```diff
@@ -23,13 +23,17 @@ const styles = createStyles({
...
+    display: "block",
+    fontSize: "12px"
   }
 });
 
-interface RadioGroupFieldProps extends WithStyles<typeof styles> {
+interface RadioGroupFieldProps {
   choices: Array<{
```
Comment (dominik-zeglen) [inline src/components/RadioGroupField/RadioGroupField.tsx]: Not changed in this PR, but it would be better if it would be named type instead of literal wrapped in `Array<T>`

File: src/components/RadioSwitchField/RadioSwitchField.tsx [hunk 8]
```diff
@@ -0,0 +1,97 @@
...
+    classes,
+    disabled,
+    error,
+    firstOptionLabel,
+    onChange,
+    name,
+    secondOptionLabel,
+    value
+  }: RadioSwitchFieldProps & WithStyles<typeof styles>) => {
+    const initialValue = value ? "visible" : "hidden";
```
Comment (dominik-zeglen) [inline src/components/RadioSwitchField/RadioSwitchField.tsx]: `visible`/`hidden` pair won't be always valid options, I can imagine situations where it would be `on`/`off` or `yes`/`no`

File: src/configuration/ConfigurationPage.tsx [hunk 9]
```diff
@@ -12,17 +12,21 @@ import { useIntl } from "react-intl";
 
 import { IconProps } from "@material-ui/core/Icon";
 import { sectionNames } from "@saleor/intl";
+import { hasPermission } from "../auth/misc";
 import { User } from "../auth/types/User";
 import Container from "../components/Container";
 import PageHeader from "../components/PageHeader";
 import { PermissionEnum } from "../types/globalTypes";
 
 export interface MenuItem {
```
Comment (dominik-zeglen) [inline src/configuration/ConfigurationPage.tsx]:
```
export interface MenuSection {
  label: string;
  menuItems: MenuItem[]
}
```
would look a lot better and descriptive

File: src/productTypes/components/ProductTypeListPage/ProductTypeListPage.tsx [hunk 10]
```diff
@@ -1,5 +1,5 @@
 import Button from "@material-ui/core/Button";
-import AddIcon from "@material-ui/icons/Add";
+
```
Comment (dominik-zeglen) [inline src/productTypes/components/ProductTypeListPage/ProductTypeListPage.tsx]: Empty line
