### PR TITLE
Fix error cleanup when switching product variants

### LINKED ISSUE #239: Input errors are not cleared when switching between variants
### Steps to reproduce the problem
1. Go to variant details page. 
2. Edit the variant to cause an error, e.g. by using the same SKU or attribute values combination that already exists.
3. Switch to a different variant.
4. The input that failed is still rendered as error.

### What I expected to happen
Switching to a new variant should clear errors.

### Screenshots

The issue was caused for "500ml" option, here I'm viewing "2l":

image

### PR DESCRIPTION
**Pull request by tomaszszymanski129**
I want to merge this change because it fixes #239 

1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Translated strings are extracted to `.pot` file.
1. [x] Number of API calls is optimized.
1. [x] The changes are tested.
1. [x] Type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

File: src/products/views/ProductVariant.tsx [hunk 1]
```diff
@@ -146,6 +144,7 @@ export const ProductVariant: React.FC<ProductUpdateProps> = ({
                     }}
                     onVariantClick={variantId => {
                       navigate(productVariantEditUrl(productId, variantId));
+                      setErrors([]);
```
Comment (dominik-zeglen) [inline src/products/views/ProductVariant.tsx]: I'd rather set it in `React.useEffect` - now errors persist if you go back using browser history.

File: src/products/views/ProductVariant.tsx [hunk 2]
```diff
@@ -35,6 +35,10 @@ export const ProductVariant: React.FC<ProductUpdateProps> = ({
   const navigate = useNavigator();
   const notify = useNotifier();
   const intl = useIntl();
+  const [errors, setErrors] = useState([]);
+  useEffect(() => {
+    setErrors([]);
+  }, [variantId]);
```
Comment (dominik-zeglen) [inline src/products/views/ProductVariant.tsx]: How about `useEffect(() => setErrors([]), [variantId]);`?
#285 will autofix this but it's not merged yet 🤷‍♂️
